import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar"; // <-- Import Navbar

export const metadata: Metadata = {
    title: "Bookie",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className="__variable_5cfdac __variable_9a8899 antialiased vsc-initialized">
                    <Navbar />
                    {children}
                </body>
            </html>
        </ClerkProvider>
    );
}
