name: Bookie Dispatcher

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

      run_build:
        description: "Run build step"
        required: true
        default: true
        type: boolean

jobs:
  dispatch-job:
    runs-on: ubuntu-latest

    steps:
      - name: Show selected inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Run Build: ${{ github.event.inputs.run_build }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        if: ${{ github.event.inputs.run_build == 'true' }}
        run: npm run build